import React from 'react'
import { Document, Page, Text, View, renderToBuffer } from '@react-pdf/renderer'
import type { Dossier } from '@/app/actions/portfolio'
import { docStyles as s, formatPdfDate } from './pdf-shared'

/**
 * Teaching activity dossier: appraisal/revalidation-ready evidence of a
 * teacher's activity — sessions taught, hours, reach, and anonymised
 * feedback themes. The mirror image of the trainee portfolio pack.
 */

export interface DossierPdfData {
  name: string
  organization: string
  periodStart: Date
  periodEnd: Date
  dossier: Dossier
}

function DossierDocument({ data }: { data: DossierPdfData }) {
  const { dossier } = data
  return (
    <Document title="Teaching Activity Dossier" author="Petrios">
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.title}>Teaching Activity Dossier</Text>
          <Text style={s.subtitle}>
            {data.name} · {data.organization}
          </Text>
          <Text style={s.subtitle}>
            Period: {formatPdfDate(data.periodStart)} – {formatPdfDate(data.periodEnd)}
          </Text>
        </View>

        <View style={s.section}>
          <Text style={s.sectionTitle}>Summary</Text>
          <Text>
            Sessions taught: {dossier.sessionsTaught.length} · Teaching hours:{' '}
            {dossier.totalHours} · Attendees reached: {dossier.totalAttendees}
            {dossier.overallAverageRating !== null
              ? ` · Average feedback rating: ${dossier.overallAverageRating}/5`
              : ''}
          </Text>
        </View>

        <View style={s.section}>
          <Text style={s.sectionTitle}>Sessions taught</Text>
          <View style={s.headRow}>
            <Text style={{ width: '40%' }}>Session</Text>
            <Text style={{ width: '18%' }}>Date</Text>
            <Text style={{ width: '12%' }}>Duration</Text>
            <Text style={{ width: '14%' }}>Attendees</Text>
            <Text style={{ width: '16%' }}>Feedback</Text>
          </View>
          {dossier.sessionsTaught.map((row, i) => (
            <View key={i} style={s.row} wrap={false}>
              <Text style={{ width: '40%' }}>{row.title}</Text>
              <Text style={{ width: '18%' }}>
                {new Date(row.date).toLocaleDateString('en-GB')}
              </Text>
              <Text style={{ width: '12%' }}>{row.durationMins} min</Text>
              <Text style={{ width: '14%' }}>{row.attendees}</Text>
              <Text style={{ width: '16%' }}>
                {row.averageRating !== null
                  ? `${row.averageRating}/5 (${row.responses})`
                  : '—'}
              </Text>
            </View>
          ))}
        </View>

        {dossier.themes.length > 0 && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Privacy-processed feedback themes</Text>
            {dossier.themes.map((theme, i) => (
              <View key={i} style={{ marginBottom: 5 }} wrap={false}>
                <Text style={{ fontWeight: 700 }}>{theme.title}</Text>
                <Text>{theme.detail}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={s.footer} fixed>
          <Text>
            Generated by Petrios from evidence-based attendance and anonymous
            session feedback. Suitable as supporting information for appraisal and
            revalidation.
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export async function generateDossierPDF(data: DossierPdfData): Promise<Buffer> {
  return Buffer.from(await renderToBuffer(<DossierDocument data={data} />))
}
