import React from 'react'
import { Document, Page, Text, View, renderToBuffer } from '@react-pdf/renderer'
import type { AttendanceLogEntry } from '@/lib/db/trainee-dashboard'
import { docStyles as s, formatPdfDate } from './pdf-shared'

/**
 * ARCP portfolio pack: verifiable teaching-attendance evidence for a
 * trainee's portfolio. Every claim in the PDF is snapshotted in
 * portfolio_packs.payload and re-renderable at /verify/pack/[packCode], so
 * an ARCP panel can confirm the document wasn't edited.
 */

export interface PortfolioPackData {
  name: string
  grade: string | null
  organization: string
  periodStart: Date
  periodEnd: Date
  entries: AttendanceLogEntry[]
  reflections: { sessionTitle: string; body: string }[]
  certificateCodes: string[]
  packCode: string
}

function sourceLabel(source: string | null): string {
  if (source === 'RECALL') return 'Audio recap catch-up'
  if (!source) return '—'
  return source.replace(/_/g, ' ').toLowerCase()
}

function PackDocument({ data }: { data: PortfolioPackData }) {
  const attended = data.entries.filter(
    (e) => e.status === 'PRESENT' || e.status === 'LATE'
  ).length

  return (
    <Document title="Teaching Portfolio Pack" author="Petrios">
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.title}>Teaching Portfolio Pack</Text>
          <Text style={s.subtitle}>
            {data.name}
            {data.grade ? ` · ${data.grade}` : ''} · {data.organization}
          </Text>
          <Text style={s.subtitle}>
            Period: {formatPdfDate(data.periodStart)} – {formatPdfDate(data.periodEnd)} ·
            Attended {attended} of {data.entries.length} sessions
          </Text>
        </View>

        <View style={s.section}>
          <Text style={s.sectionTitle}>Attendance record (evidence-based)</Text>
          <View style={s.headRow}>
            <Text style={{ width: '44%' }}>Session</Text>
            <Text style={{ width: '20%' }}>Date</Text>
            <Text style={{ width: '12%' }}>Status</Text>
            <Text style={{ width: '24%' }}>Evidence source</Text>
          </View>
          {data.entries.map((e, i) => (
            <View key={i} style={s.row} wrap={false}>
              <Text style={{ width: '44%' }}>{e.session_title}</Text>
              <Text style={{ width: '20%' }}>
                {new Date(e.session_date).toLocaleDateString('en-GB')}
              </Text>
              <Text style={{ width: '12%' }}>{e.status}</Text>
              <Text style={{ width: '24%' }}>{sourceLabel(e.primary_source)}</Text>
            </View>
          ))}
        </View>

        {data.reflections.length > 0 && (
          <View style={s.section} break>
            <Text style={s.sectionTitle}>Reflections</Text>
            {data.reflections.map((r, i) => (
              <View key={i} style={{ marginBottom: 8 }} wrap={false}>
                <Text style={{ fontWeight: 700 }}>{r.sessionTitle}</Text>
                <Text style={{ marginTop: 2 }}>{r.body}</Text>
              </View>
            ))}
          </View>
        )}

        {data.certificateCodes.length > 0 && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Certificate verification codes</Text>
            <Text>
              Verify individually at /verify/[code]: {data.certificateCodes.join(', ')}
            </Text>
          </View>
        )}

        <View style={s.footer} fixed>
          <Text>
            Generated by Petrios. Verify this pack: pack code {data.packCode} —
            /verify/pack/{data.packCode}
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export async function generatePortfolioPackPDF(data: PortfolioPackData): Promise<Buffer> {
  return Buffer.from(await renderToBuffer(<PackDocument data={data} />))
}
