import { createPrivateKey, createPublicKey, sign, verify, type KeyObject } from 'node:crypto'

/**
 * Federation v1: signed, portable teaching records. Each instance holds an
 * Ed25519 identity (INSTANCE_SIGNING_KEY, generated by
 * scripts/generate-instance-key.mjs); exports are signed over a canonical
 * JSON form so any other instance — or anyone with the issuer's public key
 * from /.well-known/petrios — can verify a record offline. This is
 * how a trainee's verified history survives rotating between trusts running
 * independent deployments.
 */

export const TEACHING_RECORD_FORMAT = 'petrios-record/v1'

/** Deterministic JSON: recursively sorted object keys, no whitespace. */
export function canonicalize(value: unknown): string {
  if (value === null || typeof value !== 'object') {
    return JSON.stringify(value)
  }
  if (Array.isArray(value)) {
    return `[${value.map(canonicalize).join(',')}]`
  }
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([k, v]) => `${JSON.stringify(k)}:${canonicalize(v)}`)
  return `{${entries.join(',')}}`
}

export function isFederationConfigured(): boolean {
  return !!process.env.INSTANCE_SIGNING_KEY
}

function getPrivateKey(): KeyObject {
  const seed = process.env.INSTANCE_SIGNING_KEY
  if (!seed) throw new Error('INSTANCE_SIGNING_KEY is not configured')
  return createPrivateKey({ key: Buffer.from(seed, 'base64'), format: 'der', type: 'pkcs8' })
}

/** This instance's public key (SPKI DER, base64) for /.well-known. */
export function getInstancePublicKey(): string {
  const publicKey = createPublicKey(getPrivateKey())
  return publicKey.export({ format: 'der', type: 'spki' }).toString('base64')
}

/** Sign a payload (the record WITHOUT its signature field). */
export function signPayload(payload: Record<string, unknown>): string {
  return sign(null, Buffer.from(canonicalize(payload)), getPrivateKey()).toString('base64')
}

/** Verify a payload against a base64 signature and SPKI-DER base64 key. */
export function verifyPayload(
  payload: Record<string, unknown>,
  signatureB64: string,
  publicKeyB64: string
): boolean {
  try {
    const publicKey = createPublicKey({
      key: Buffer.from(publicKeyB64, 'base64'),
      format: 'der',
      type: 'spki',
    })
    return verify(
      null,
      Buffer.from(canonicalize(payload)),
      publicKey,
      Buffer.from(signatureB64, 'base64')
    )
  } catch {
    return false
  }
}

export interface TeachingRecord {
  format: typeof TEACHING_RECORD_FORMAT
  issuer: string
  issued_at: string
  public_key: string
  subject: { name: string; grade: string | null }
  attendance: { session: string; date: string; status: string; source: string | null }[]
  certificates: string[]
  coverage: { domain: string; sessions: number }[]
  signature: string
}

/** Split a parsed record into its signed payload + signature. */
export function splitRecord(record: TeachingRecord): {
  payload: Record<string, unknown>
  signature: string
} {
  const { signature, ...payload } = record
  return { payload, signature }
}
